### ISSUE TITLE
SRVE0777E: Exception thrown by application class 'com.ibm.ws.container.service.metadata.internal.MetaDataServiceImpl.getMetaData:268'

### ISSUE THREAD

**Issue by spitfire88** [blueperf/acmeair-authservice-java#14]
The acme-mainservice po runs successfully but the rest show this warning. The corresponding docker logs through the exception. 

k describe po acmeair-authservice-d87466b77-p9xp4

>   Normal   Scheduled  3m50s                  default-scheduler             Successfully assigned default/acmeair-authservice-d87466b77-p9xp4 to beta.spitfire.local
  Normal   Pulled     3m49s                  kubelet, beta.spitfire.local  Container image "acmeair-authservice-java:latest" already present on machine
  Normal   Created    3m49s                  kubelet, beta.spitfire.local  Created container acmeair-authservice-java
  Normal   Started    3m49s                  kubelet, beta.spitfire.local  Started container acmeair-authservice-java
  Warning  Unhealthy  112s (x22 over 3m36s)  kubelet, beta.spitfire.local  Readiness probe failed: HTTP probe failed with statuscode: 500

docker logs 

> [AUDIT   ] CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 8.917 seconds.
[AUDIT   ] CWPKI0803A: SSL certificate created in 5.769 seconds. SSL key file: /opt/ibm/wlp/output/defaultServer/resources/security/key.p12
[ERROR   ] SRVE0777E: Exception thrown by application class 'com.ibm.ws.container.service.metadata.internal.MetaDataServiceImpl.getMetaData:268'
java.lang.IllegalStateException: WEB#acmeair-bookingservice-java-3.0.0-SNAPSHOT#acmeair-bookingservice-java-3.0.0-SNAPSHOT.war
        at com.ibm.ws.container.service.metadata.internal.MetaDataServiceImpl.getMetaData(MetaDataServiceImpl.java:268)
        at [internal classes]
[ERROR   ] SRVE0315E: An exception occurred: java.lang.Throwable: java.lang.IllegalStateException: WEB#acmeair-bookingservice-java-3.0.0-SNAPSHOT#acmeair
-bookingservice-java-3.0.0-SNAPSHOT.war
        at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5051)
        at [internal classes]

Any pointers on this?

**Comment by jdmcclur** [comment]
My guess is this: https://github.com/OpenLiberty/open-liberty/issues/8573
This will be fixed soon, but as a workaround, you can edit the server.xml to make the app name the same as the war name (acmeair-bookingservice-java-3.0.0-SNAPSHOT).

**Comment by jdmcclur** [comment]
This is fixed now.
